// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PYS.Infrastructure.Persistence.Context;

#nullable disable

namespace PYS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250706145452_AddFormsAndFormDetailsTables3")]
    partial class AddFormsAndFormDetailsTables3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PYS.Core.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.FormDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IndicatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.HasIndex("FormId");

                    b.HasIndex("IndicatorId");

                    b.ToTable("FormDetails");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.FormTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.ToTable("FormTypes");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.FormTypesPeriods", b =>
                {
                    b.Property<Guid>("FormTypesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FormTypesId", "PeriodsId");

                    b.HasIndex("PeriodsId");

                    b.ToTable("FormTypesPeriods");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Forms", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormTypeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Indicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataCalculation")
                        .HasColumnType("int");

                    b.Property<string>("DataCalculationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("DataSourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("int");

                    b.Property<string>("EvaluationTypeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormTypeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorDetailDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IndicatorKmaxDesc")
                        .HasColumnType("float");

                    b.Property<double>("IndicatorKminDesc")
                        .HasColumnType("float");

                    b.Property<string>("IndicatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorPeriodText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorPlannedDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorRealizedDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorResultDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.HasIndex("FormTypeId");

                    b.ToTable("Indicators");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.LocationPeriods", b =>
                {
                    b.Property<Guid>("LocationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationsId", "PeriodsId");

                    b.HasIndex("PeriodsId");

                    b.ToTable("LocationPeriods");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Periods", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasStaging")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IndicatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StageLower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StageTop")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.HasIndex("IndicatorId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55929733-870b-4895-b62b-b9249fa86a06"),
                            ConcurrencyStamp = "f695f426-eb84-437f-89fd-a55b50c9f813",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLDAP")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("037ffd4d-e033-4220-b044-c4c6eddad883"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4dd8df53-bcb9-4dcb-8290-0cc2964efc11",
                            CreatedDate = new DateTime(2025, 7, 6, 17, 54, 52, 64, DateTimeKind.Local).AddTicks(9338),
                            CreatedIp = "::1",
                            Email = "atazegul@santafarma.com.tr",
                            EmailConfirmed = true,
                            IsActive = true,
                            IsLDAP = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ATAZEGUL@SANTAFARMA.COM.TR",
                            NormalizedUserName = "ATAZEGUL@SANTAFARMA.COM.TR",
                            PasswordHash = "AQAAAAIAAYagAAAAEN3TkHjTOkxlxwXGalRs5k6bwZ3onpUYGYDzCVa4c4wgSOAzk/rzPbBqJJpsNNxFdA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RegistrationNumber = 103100,
                            SecurityStamp = "3b564a88-8f8c-4811-9227-510552859078",
                            TwoFactorEnabled = false,
                            UserName = "atazegul@santafarma.com.tr"
                        });
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("037ffd4d-e033-4220-b044-c4c6eddad883"),
                            RoleId = new Guid("55929733-870b-4895-b62b-b9249fa86a06")
                        });
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Category", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.FormDetails", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PYS.Core.Domain.Entities.Forms", "Form")
                        .WithMany("FormDetails")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PYS.Core.Domain.Entities.Indicator", "Indicator")
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");

                    b.Navigation("Form");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.FormTypes", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.FormTypesPeriods", b =>
                {
                    b.HasOne("PYS.Core.Domain.Entities.FormTypes", "FormType")
                        .WithMany("FormTypesPeriods")
                        .HasForeignKey("FormTypesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PYS.Core.Domain.Entities.Periods", "Period")
                        .WithMany("FormTypesPeriods")
                        .HasForeignKey("PeriodsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormType");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Forms", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Indicator", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PYS.Core.Domain.Entities.FormTypes", "FormType")
                        .WithMany()
                        .HasForeignKey("FormTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");

                    b.Navigation("FormType");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Location", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.LocationPeriods", b =>
                {
                    b.HasOne("PYS.Core.Domain.Entities.Location", "Location")
                        .WithMany("LocationPeriods")
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PYS.Core.Domain.Entities.Periods", "Period")
                        .WithMany("LocationPeriods")
                        .HasForeignKey("PeriodsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Periods", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Product", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PYS.Core.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Stage", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PYS.Core.Domain.Entities.Indicator", "Indicator")
                        .WithMany("Stages")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppRoleClaim", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserClaim", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserLogin", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserRole", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserToken", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.FormTypes", b =>
                {
                    b.Navigation("FormTypesPeriods");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Forms", b =>
                {
                    b.Navigation("FormDetails");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Indicator", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Location", b =>
                {
                    b.Navigation("LocationPeriods");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Periods", b =>
                {
                    b.Navigation("FormTypesPeriods");

                    b.Navigation("LocationPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
