// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PYS.Infrastructure.Persistence.Context;

#nullable disable

namespace PYS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250521074531_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PYS.Core.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55929733-870b-4895-b62b-b9249fa86a06"),
                            ConcurrencyStamp = "6f660bb2-1a96-47a3-a0b7-81398feb467b",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AppUserCreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLDAP")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserCreatedId");

                    b.HasIndex("AppUserModifiedId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("037ffd4d-e033-4220-b044-c4c6eddad883"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3bde6817-beba-4100-b5fd-4bd541ea9baa",
                            CreatedDate = new DateTime(2025, 5, 21, 10, 45, 30, 969, DateTimeKind.Local).AddTicks(6466),
                            CreatedIp = "::1",
                            Email = "atazegul@santafarma.com.tr",
                            EmailConfirmed = true,
                            IsActive = true,
                            IsLDAP = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ATAZEGUL@SANTAFARMA.COM.TR",
                            NormalizedUserName = "ATAZEGUL@SANTAFARMA.COM.TR",
                            PasswordHash = "AQAAAAIAAYagAAAAEJcgxbkbTal8AiURaEbnLv4YbTPx3G0S7ZhJPnLuEJ18c1Z0gbdd/e00VPYwOqYCOg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RegistrationNumber = 103100,
                            SecurityStamp = "69c48223-b1fa-4720-ac0e-5334c5f3a64a",
                            TwoFactorEnabled = false,
                            UserName = "atazegul@santafarma.com.tr"
                        });
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("037ffd4d-e033-4220-b044-c4c6eddad883"),
                            RoleId = new Guid("55929733-870b-4895-b62b-b9249fa86a06")
                        });
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Category", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Product", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PYS.Core.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppRoleClaim", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserCreated")
                        .WithMany()
                        .HasForeignKey("AppUserCreatedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", "AppUserModified")
                        .WithMany()
                        .HasForeignKey("AppUserModifiedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUserCreated");

                    b.Navigation("AppUserModified");
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserClaim", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserLogin", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserRole", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SantaFarma.Architecture.Core.Domain.Entities.AppUserToken", b =>
                {
                    b.HasOne("SantaFarma.Architecture.Core.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PYS.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
